ratings:
  All:
    description: ""
    classType: default
  Tier 1:
    description: "Great food and service. A treat."
    classType: success
  Tier 2:
    description: "Memorable experience, worthy of return visits."
    classType: primary
  Tier 3:
    description: "Acceptable value but in no hurry to return."
    classType: black
  Tier 4:
    description: "Substandard value or execution."
    classType: warning
  Solid:
    description: "Pleasing food or experience."
    classType: info
  Decent:
    description: "Better than average, but just barely."
    classType: black
  Mediocre:
    description: "Average, unworthy of special attention."
    classType: default
  Hellscape:
    description: "Avoid at all costs."
    classType: danger

tiers:
  Somerville:
    Davis Sq:
      Posto: "Tier 3"
      The Table at Season To Taste: "Tier 3"
      3 Little Figs: "Solid"
      Dave’s Fresh Pasta: "Solid"
      Painted Burro's Nachos: "Solid"
      Painted Burro: "Mediocre"
      Qingdao Garden: "Solid"
      Cafe Barada: "Mediocre"
      Diesel: "Mediocre"
      Five Horses Tavern: "Mediocre"
      Hana Sushi: "Mediocre"
      Meju: "Mediocre"
      Redbones: "Mediocre"
      Saloon: "Hellscape"
      Sugidama: "Mediocre"
      Blue Shirt Cafe: "Hellscape"
      Foundry on Elm: "Hellscape"
      Orleans: "Hellscape"
      Out of the Blue: "Hellscape"
      Urban Hearth: "Hellscape"
      Spoke Wine Bar: "Tier 1"

    Porter Sq:
      Guilia: "Tier 1"
      Forage: "Tier 3"
      Shepard: "Tier 3"
      Gran Gusto: "Tier 4"
      Cambridge Common: "Mediocre"
      Trattoria Pulcinella: "Mediocre"
      Christopher's: "Hellscape"
      Tavern in the Square: "Hellscape"
      Abbey: "Hellscape"
      Baraka Cafe: "Hellscape"
      Temple Bar: "Hellscape"

    Union Sq:
      Backbar: "Tier 3"
      Bronwyn: "Tier 3"
      Tasting Counter: "Tier 2"
      Juliet: "Tier 3"
      Casa B: "Tier 4"
      Field & Vine: "Tier 3"

    Other:
      Sarma: "Tier 1"
      La Brasa: "Tier 2"
      Fat Hen: "Tier 2"
      Kirkland Tap and Trotter: "Tier 3"
      Dali: "Tier 3"
      Kebab Factory: "Mediocre"
      Highland Kitchen: "Decent"

  Cambridge:
    Inman Sq:
      Puritan & Co: "Tier 2"
      BisQ: "Tier 3"
      Bergamot: "Tier 3"
      Ole: "Tier 4"
      Loyal Nine: "Tier 4"
      Punjhabi Dhaba: "Solid"
      Trina's: "Mediocre"
      City Girl Cafe: "Mediocre"
      All Star Sandwich: "Mediocre"
      All Star Pizza: "Mediocre"
      Tupelo: "Hellscape"
      Clover: "Hellscape"
      Ginger Exchange: "Hellscape"
      Midwest Grill: "Hellscape"
      Muqueca: "Hellscape"

    Harvard Sq:
      Alden and Harlow: "Tier 1"
      Parsnip: "Tier 3"
      Russell House Tavern: "Tier 3"
      Harvest: "Tier 4"
      Henrietta's Table: "Tier 4"
      Tasty Burger: "Decent"
      The Maharaja: "Decent"
      Grafton Street: "Hellscape"
      Border Cafe: "Hellscape"

    Central Sq:
      Cafe Sushi: "Tier 2"
      Craigie on Main: "Tier 2"
      Salts: "Tier 3"
      Little Donkey: "Tier 3"
      Viale: "Tier 3"
      Garden at the Cellar: "Tier 3"
      Central Kitchen: "Tier 4"
      Thelonious Monkfish: "Mediocre"
      Waypoint: "Tier 4"
      The Cellar: "Decent"
      Pammy's: "Tier 3"
      Flour Bakery: "Solid"
      Green Street: "Mediocre"
      Miracle of Science: "Mediocre"
      Cafe Rangzen: "Hellscape"
      Pepper Sky: "Hellscape"
      Asmara: "Hellscape"
      Cuchi Cuchi: "Hellscape"

    Kendall Sq:
      Oleana: "Tier 1"
      Cafe ArtScience: "Tier 3"
      Bondir: "Tier 3"
      Fuji: "Decent"
      Area Four Cambridge: "Mediocre"
      Commonwealth: "Tier 4"
      Catalyst: "Tier 4"
      Helmand: "Tier 4"
      Dante: "Tier 4"
      Mulan: "Solid"
      Koreana: "Mediocre"
      Desfina: "Decent"
      Emmas: "Mediocre"
      Bon Me: "Decent"
      State Park: "Decent"
      Similans: "Mediocre"
      Lord Hobo: "Mediocre"
      Area Four: "Mediocre"
      Acituna: "Mediocre"
      Tatte Bakery: "Mediocre"
      Evoo: "Hellscape"
      Za: "Hellscape"
      Abigail's: "Hellscape"
      Kika Tapas: "Hellscape"
      Meadhall: "Hellscape"
      Squeaky Beaker: "Hellscape"
      ArtBar: "Hellscape"
      Bambara: "Hellscape"
      Second St. Cafe: "Hellscape"
      Friendly Toast: "Hellscape"
      Cambridge Brewing Company: "Hellscape"

  Boston:
    Downtown:
      O Ya: "Tier 1"
      Ostra: "Tier 2"
      Boston Chops: "Tier 3"
      Yvonne's: "Tier 3"
      Grill 23 & Bar: "Tier 3"
      Scampo: "Tier 4"
      Select Oyster Bar: "Tier 4"
      Erbaluce: "Tier 3"
      Top of the Hub: "Hellscape"
      Townsman: "Tier 4"

    Back Bay:
      Deuxave: "Tier 2"
      Asta: "Tier 3"
      L’espalier: "Tier 3"
      Atlantic Fish Company: "Tier 3"
      Eastern Standard: "Tier 3"
      Fogo de Chao Brazilian Steakhouse: "Tier 4"
      UNI: "Tier 3"
      Sorellina: "Tier 3"


    Seaport:
      Row 34: "Tier 2"
      Menton: "Tier 2"
      Ocean Prime: "Tier 4"

    Kenmore Sq:
      Island Creek Oyster Bar: "Tier 2"

    North End:
      Neptune Oyster: "Tier 2"

    South End:
      Toro: "Tier 2"
      Bar Mezzana: "Tier 2"
      Butcher Shop: "Tier 3"
      Oishii Boston: "Tier 3"
      Mistral: "Tier 2"
      SRV: "Tier 3"

    Park Street:
      No. 9 Park: "Tier 4"
      Silvertone: "Hellscape"

    Fenway:
      Citizen Public House: "Solid"
      Sweet cheeks: "Mediocre"
